"""Initial CO/SO keyword registry for AERMOD v26135."""

from ..models import KeywordSpec, ParameterKind, ParameterSpec, Pathway
from .evidence import QRG_CONTROL, QRG_SOURCE

P = ParameterSpec

KEYWORDS: tuple[KeywordSpec, ...] = (
    KeywordSpec(
        Pathway.CONTROL,
        "TITLEONE",
        min_args=1,
        max_args=None,
        order=10,
        evidence=(QRG_CONTROL,),
    ),
    KeywordSpec(
        Pathway.CONTROL,
        "TITLETWO",
        min_args=1,
        max_args=None,
        order=20,
        evidence=(QRG_CONTROL,),
    ),
    KeywordSpec(
        Pathway.CONTROL,
        "MODELOPT",
        parameters=(P("option"),),
        min_args=1,
        max_args=None,
        mandatory=True,
        order=30,
        evidence=(QRG_CONTROL,),
    ),
    KeywordSpec(
        Pathway.CONTROL,
        "AVERTIME",
        min_args=1,
        max_args=None,
        mandatory=True,
        order=40,
        evidence=(QRG_CONTROL,),
    ),
    KeywordSpec(
        Pathway.CONTROL,
        "POLLUTID",
        min_args=1,
        max_args=2,
        mandatory=True,
        order=50,
        evidence=(QRG_CONTROL,),
    ),
    KeywordSpec(
        Pathway.CONTROL,
        "RUNORNOT",
        parameters=(P("run", ParameterKind.ENUM, choices=("RUN", "NOT")),),
        min_args=1,
        max_args=1,
        mandatory=True,
        order=900,
        evidence=(QRG_CONTROL,),
    ),
    KeywordSpec(
        Pathway.CONTROL,
        "INCLUDED",
        parameters=(P("filename", ParameterKind.PATH),),
        min_args=1,
        max_args=1,
        repeatable=True,
        order=850,
        evidence=(QRG_CONTROL,),
    ),
    KeywordSpec(
        Pathway.SOURCE,
        "ELEVUNIT",
        min_args=1,
        max_args=1,
        order=10,
        evidence=(QRG_SOURCE,),
    ),
    KeywordSpec(
        Pathway.SOURCE,
        "LOCATION",
        min_args=4,
        max_args=9,
        repeatable=True,
        mandatory=True,
        order=20,
        evidence=(QRG_SOURCE,),
    ),
    KeywordSpec(
        Pathway.SOURCE,
        "SRCPARAM",
        min_args=3,
        max_args=7,
        repeatable=True,
        mandatory=True,
        order=30,
        evidence=(QRG_SOURCE,),
    ),
    KeywordSpec(
        Pathway.SOURCE,
        "INCLUDED",
        parameters=(P("filename", ParameterKind.PATH),),
        min_args=1,
        max_args=1,
        repeatable=True,
        order=900,
        evidence=(QRG_SOURCE,),
    ),
    KeywordSpec(
        Pathway.SOURCE,
        "SRCGROUP",
        min_args=2,
        max_args=None,
        repeatable=True,
        mandatory=True,
        order=1000,
        evidence=(QRG_SOURCE,),
        notes=("SRCGROUP must be the final source keyword before SO FINISHED.",),
    ),
)
